parameters:
#    tutorial.example.class: Waramy\TutorialBundle\Example

services:
#    tutorial.example:
#        class: %tutorial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
