parameters:
#    insurance.example.class: Waramy\InsuranceBundle\Example

services:
#    insurance.example:
#        class: %insurance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
