accounting:
    resource: "@AccountingBundle/Resources/config/routing.yml"
    prefix:   /

ad:
    resource: "@AdBundle/Resources/config/routing.yml"
    prefix:   /

contract:
    resource: "@ContractBundle/Resources/config/routing.yml"
    prefix:   /

vehicle:
    resource: "@VehicleBundle/Resources/config/routing.yml"
    prefix:   /

tutorial:
    resource: "@TutorialBundle/Resources/config/routing.yml"
    prefix:   /

fiscal:
    resource: "@FiscalBundle/Resources/config/routing.yml"
    prefix:   /

insurance:
    resource: "@InsuranceBundle/Resources/config/routing.yml"
    prefix:   /

medias:
    resource: "@MediasBundle/Resources/config/routing.yml"
    prefix:   /

address:
    resource: "@AddressBundle/Resources/config/routing.yml"
    prefix:   /

professional:
    resource: "@ProfessionalBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

