parameters:
#    waramy_medias.example.class: Waramy\MediasBundle\Example

services:
#    waramy_medias.example:
#        class: %waramy_medias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
