parameters:
#    medias.example.class: Waramy\MediasBundle\Example

services:
#    medias.example:
#        class: %medias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
