parameters:
#    waramy_accounting.example.class: Waramy\AccountingBundle\Example

services:
#    waramy_accounting.example:
#        class: %waramy_accounting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
