parameters:
#    accounting.example.class: Waramy\AccountingBundle\Example

services:
#    accounting.example:
#        class: %accounting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
