parameters:
#    waramy_vehicle.example.class: Waramy\VehicleBundle\Example

services:
#    waramy_vehicle.example:
#        class: %waramy_vehicle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
