parameters:
#    vehicle.example.class: Waramy\VehicleBundle\Example

services:
#    vehicle.example:
#        class: %vehicle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
